RUNNING QUERIES

In [12]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("/Users/wilson/AttentionLab/data/attentionlab.db")

In [13]:
# Top 10 videos by views    

top_videos = pd.read_sql("""
SELECT
    caption,
    platform,
    topic,
    format,
    views
FROM videos
ORDER BY views DESC
LIMIT 10;
""", conn)

top_videos

                      caption        platform         topic     format  views
0  Finance Tip Everyone Needs          TikTok       Finance   Tutorial  61300
1          AI Automation Demo          TikTok            AI       Demo  52100
2      Best AI Tool This Week          TikTok            AI     Review  48200
3              AI Side Hustle          TikTok            AI  Challenge  45800
4       Best Productivity App          TikTok  Productivity     Review  40200
5         Data Analyst Skills          TikTok        Career   Tutorial  38900
6                  SQL Tip #1          TikTok        Coding   Tutorial  37100
7                Study Faster  YouTube Shorts    Study Tips   Tutorial  34300
8        Python in 60 Seconds  YouTube Shorts        Coding   Tutorial  32000
9                 Tech Trends  YouTube Shorts     Tech News   Listicle  30500

In [14]:
# 10 videos by engagement rate (likes + comments / views)  
best_platform = pd.read_sql("""
SELECT
    platform,
    COUNT(*) AS video_count,
    ROUND(AVG(views), 2) AS avg_views,
    SUM(views) AS total_views
FROM videos
GROUP BY platform
ORDER BY avg_views DESC;
""", conn)

best_platform

          platform  video_count  avg_views  total_views
0           TikTok           12   34866.67       418400
1   YouTube Shorts            9   27277.78       245500
2  Instagram Reels            9   17677.78       159100

In [15]:
# Best platform by average views
best_topic = pd.read_sql("""
SELECT
    topic,
    COUNT(*) AS video_count,
    ROUND(AVG(views), 2) AS avg_views,
    SUM(views) AS total_views
FROM videos
GROUP BY topic
ORDER BY avg_views DESC;
""", conn)

best_topic

          topic  video_count  avg_views  total_views
0       Finance            2   42400.00        84800
1            AI            5   40660.00       203300
2  Productivity            3   29266.67        87800
3        Coding            4   28975.00       115900
4        Career            3   23800.00        71400
5     Marketing            3   22566.67        67700
6    Study Tips            3   22466.67        67400
7     Tech News            3   21366.67        64100
8      Business            3   16800.00        50400
9     Lifestyle            1   10200.00        10200

In [16]:
# Best format for engagement rate
best_format = pd.read_sql("""
SELECT
    format,
    COUNT(*) AS video_count,
    ROUND(AVG(engagement_rate), 4) AS avg_engagement_rate,
    ROUND(AVG(views), 2) AS avg_views
FROM videos
GROUP BY format
ORDER BY avg_engagement_rate DESC;
""", conn)

best_format

         format  video_count  avg_engagement_rate  avg_views
0        Review            4               6.9641   29000.00
1      Tutorial            7               3.7180   35700.00
2      Listicle            2               1.6717   26450.00
3     Challenge            1               1.4566   45800.00
4    Case Study            6               1.3096   24166.67
5      Reaction            2               1.2306   24950.00
6          Demo            3               1.1533   27800.00
7  Storytelling            5               0.9698   16020.00

In [17]:
# Best hook type by engagment rate   
best_hook = pd.read_sql("""
SELECT
    hook_type,
    COUNT(*) AS video_count,
    ROUND(AVG(views), 2) AS avg_views,
    ROUND(AVG(engagement_rate), 4) AS avg_engagement_rate
FROM videos
GROUP BY hook_type
ORDER BY avg_views DESC;
""", conn)

best_hook

          hook_type  video_count  avg_views  avg_engagement_rate
0  Problem Solution            3   45733.33               2.8861
1     Shocking Fact            3   34966.67               8.2798
2     Tutorial Hook            5   32100.00               2.6915
3        Case Study            1   24800.00               0.7166
4        Story Hook            7   24642.86               1.5540
5          Hot Take            4   22000.00               1.4988
6           Mistake            4   20500.00               2.3926
7          Question            3   17700.00               1.0648

In [18]:
# Best video legnth bucket by engagement rate
best_length = pd.read_sql("""
SELECT
    length_bucket,
    COUNT(*) AS video_count,
    ROUND(AVG(views), 2) AS avg_views,
    ROUND(AVG(engagement_rate), 4) AS avg_engagement_rate
FROM videos
GROUP BY length_bucket
ORDER BY avg_views DESC;
""", conn)

best_length

  length_bucket  video_count  avg_views  avg_engagement_rate
0     15-30 sec           12   33641.67               4.0967
1     31-60 sec           18   23294.44               1.5639

In [19]:
# Best day of the week by engagement rate
best_day = pd.read_sql("""
SELECT
    day_of_week,
    COUNT(*) AS video_count,
    ROUND(AVG(views), 2) AS avg_views,
    ROUND(AVG(engagement_rate), 4) AS avg_engagement_rate
FROM videos
GROUP BY day_of_week
ORDER BY avg_views DESC;
""", conn)

best_day

  day_of_week  video_count  avg_views  avg_engagement_rate
0      Friday            5    37360.0               5.9442
1     Tuesday            4    28800.0               2.2256
2      Sunday            4    27275.0               2.9166
3    Thursday            4    26125.0               1.4025
4   Wednesday            4    25500.0               1.1603
5    Saturday            5    24180.0               2.1382
6      Monday            4    21125.0               1.5193

In [20]:
# Weekday vs Weekend by engagement rate
weekend_analysis = pd.read_sql("""
SELECT
    is_weekend,
    COUNT(*) AS video_count,
    ROUND(AVG(views), 2) AS avg_views,
    ROUND(AVG(engagement_rate), 4) AS avg_engagement_rate
FROM videos
GROUP BY is_weekend;
""", conn)

weekend_analysis

   is_weekend  video_count  avg_views  avg_engagement_rate
0           0           21   28238.10               2.6168
1           1            9   25555.56               2.4842

In [24]:
# Production ROI by views
production_roi = pd.read_sql("""
SELECT
    caption,
    platform,
    topic,
    views,
    editing_time_minutes,
    ROUND(views_per_minute, 2) AS views_per_minute
FROM videos
ORDER BY views_per_minute DESC
LIMIT 10;
""", conn)

production_roi

,caption,platform,topic,views,editing_time_minutes,views_per_minute
0,Finance Tip Everyone Needs,TikTok,Finance,61300,20,3065.00
1,Excel Shortcut,Instagram Reels,Productivity,26800,10,2680.00
2,SQL Tip #1,TikTok,Coding,37100,15,2473.33
3,Data Analyst Skills,TikTok,Career,38900,25,1556.00
4,Tech Trends,YouTube Shorts,Tech News,30500,20,1525.00
5,Productivity Myth,YouTube Shorts,Productivity,20800,15,1386.67
6,AI Side Hustle,TikTok,AI,45800,35,1308.57
7,AI Automation Demo,TikTok,AI,52100,45,1157.78
8,Best Productivity App,TikTok,Productivity,40200,35,1148.57
9,Best AI Tool This Week,TikTok,AI,48200,45,1071.11

In [25]:
# Best topic by follower conversion 
follower_conversion = pd.read_sql("""
SELECT
    topic,
    COUNT(*) AS video_count,
    ROUND(AVG(follower_conversion_rate), 4) AS avg_follower_conversion_rate,
    SUM(followers_gained) AS total_followers_gained
FROM videos
GROUP BY topic
ORDER BY avg_follower_conversion_rate DESC;
""", conn)

follower_conversion

,topic,video_count,avg_follower_conversion_rate,total_followers_gained
0,Finance,2,0.0048,440
1,AI,5,0.0043,905
2,Coding,4,0.0039,460
3,Study Tips,3,0.0038,283
4,Productivity,3,0.0037,345
5,Marketing,3,0.0035,255
6,Tech News,3,0.0032,215
7,Career,3,0.0030,250
8,Business,3,0.0028,142
9,Lifestyle,1,0.0025,25

In [27]:
# Low-effort high-return videos
low_effort_high_return = pd.read_sql("""
SELECT
    caption,
    platform,
    topic,
    views,
    editing_time_minutes,
    ROUND(views_per_minute, 2) AS views_per_minute
FROM videos
WHERE editing_time_minutes <= 35
ORDER BY views_per_minute DESC
LIMIT 10;
""", conn)

low_effort_high_return

,caption,platform,topic,views,editing_time_minutes,views_per_minute
0,Finance Tip Everyone Needs,TikTok,Finance,61300,20,3065.00
1,Excel Shortcut,Instagram Reels,Productivity,26800,10,2680.00
2,SQL Tip #1,TikTok,Coding,37100,15,2473.33
3,Data Analyst Skills,TikTok,Career,38900,25,1556.00
4,Tech Trends,YouTube Shorts,Tech News,30500,20,1525.00
5,Productivity Myth,YouTube Shorts,Productivity,20800,15,1386.67
6,AI Side Hustle,TikTok,AI,45800,35,1308.57
7,Best Productivity App,TikTok,Productivity,40200,35,1148.57
8,Study Faster,YouTube Shorts,Study Tips,34300,35,980.00
9,Tech News Recap,YouTube Shorts,Tech News,22400,25,896.00

In [28]:
conn.close()